# Generated by Django 4.2 on 2026-04-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Round History'},
        ),
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_unique_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('session', 'player_unique_id')},
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['session', 'round_number'], name='bets_session_7af54e_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['session', 'round_number'], name='history_session_5928f2_idx'),
        ),
    ]
