FROM node:20-slim AS builder

WORKDIR /app/frontend

COPY frontend/package.json ./package.json

ENV NODE_OPTIONS=--openssl-legacy-provider

RUN npm install

COPY frontend/src ./src
COPY frontend/public ./public

RUN npm run build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/frontend/build /usr/share/nginx/html

COPY infra/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
